### ISSUE TITLE
[Feature] - Resolve require calls relatively to `process.cwd()` instead of `__dirname`

### ISSUE THREAD

**Issue by goranmoomin** [3Nigma/nelu-kernelu#2]
I would like to require files in the notebook; however I'm not sure how the files are resolved...
I tried to `require` relatively to the notebook and the `jupyter` root directory but both failed.

**Comment by goranmoomin** [comment]
Ok, I've learnt that since `__dirname` is a file in the cloned repo, I can require files relatively to them.
This really isn't intuitive behavior; however I'm not sure if this can be fixed.
Are there any workarounds from this?
![image](https://user-images.githubusercontent.com/37990858/65122156-41914880-da2b-11e9-8a9c-fdcbb02318e7.png)

**Comment by 3Nigma** [comment]
Hey there,
We'll discuss this internally today, but I believe there is a solution to it: **we'll add `process.cwd()` to the resolution path of `require`**. That way, when you'll require a relative module, it will also try to locate it starting from the same directory in which the current notebook lies.
If this is acceptable, it might prove an easy fix.
