### ISSUE TITLE
[Feature] - `kernel.print` should print objects more friendlier

### ISSUE THREAD

**Issue by goranmoomin** [3Nigma/nelu-kernelu#3]
Currently the `kernel.print` balks on non-strings (i.e. objects) and using `.toString()` prints all objects as `[object Object]`, which isn't really helpful when inspecting objects by printing.

I would very appreciate if printing objects result in a hierarchical tree like the ones in the browser debuggers, but for now using [`util.print`](https://nodejs.org/dist/latest-v12.x/docs/api/util.html#util_util_format_format_args) (which are [used in console.log](https://nodejs.org/dist/latest-v12.x/docs/api/console.html#console_console_log_data_args)) should be sufficient.

**Comment by 3Nigma** [comment]
Good idea/catch! We'll have it done.
