### ISSUE TITLE
Where do you install NPM modules for use in notebook?

### ISSUE THREAD

**Issue by jbreadner** [3Nigma/nelu-kernelu#8]
Installing an npm module like 'mssql' in the nelu-kernelu directory does not make that module accessible for use in notebook code.  Installing modules globally works, but is not clean.  Where can we install NPM modules to make them accessible to Jupyter?

**Comment by goranmoomin** [comment]
@jbreadner You can install the modules in the directory the jupyter notebook is running. As #2 is resolved, installing & requiring would work without hassle.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 3Nigma** [comment]
Hey @jbreadner ! Thank you for your interest in the project.
Having #2 resolved allows us to, as @pcr910303 said, resolve npm-module `require`ments located on the same directory level as the active notebook itself. I think this is what you're looking for.
